;; -*- no-byte-compile: t; -*-
;;; ~/dev/dotfiles/emacs/.doom.d/packages.el

(package! async)
(package! cider)
(package! clj-refactor)
(package! clojure-mode)
(package! company)
(package! company-lsp)
(package! dap-mode)
(package! dart-mode)
(package! dart-server)
(package! flutter)
(package! flycheck-clojure)
(package! flycheck-clj-kondo :disable t)
(package! hover)
(package! lsp-java)
(package! lsp-mode)
(package! lsp-ui)
(package! lsp-treemacs)
(package! nyan-mode)
(package! scss-mode)
(package! paredit)
(package! parrot :recipe (:host github :repo "jnc-nj/parrot" :branch "master"))
