;; -*- no-byte-compile: t; -*-
;;; ~/dev/dotfiles/emacs/.doom.d/packages.el

(package! cider)
(package! clj-refactor)
(package! clojure-mode)
(package! dap-mode)
(package! dart-mode)
(package! emidje)
(package! flutter)
(package! flycheck-clojure)
(package! flycheck-package)
(package! hover)
(package! lsp-dart)
;; (package! lsp-dart :recipe (:local-repo "~/dev/lsp-dart" :files ("*.el") :no-byte-compile t))
(package! lsp-java)
(package! lsp-mode)
(package! lsp-ui)
(package! lsp-treemacs)
(package! scss-mode)
(package! paredit)
(package! parrot :recipe (:host github :repo "jnc-nj/parrot" :branch "master"))
(package! posframe)
(package! yaml-mode)

(unpin! (:lang dart))
(unpin! treemacs)
(unpin! lsp-treemacs)
(unpin! dap-mode)
(unpin! (:lang dart) (:tools debugger))
