#!/usr/bin/env bash

source $HOME/.critical-keys
source $HOME/.env

killall sxhkd &
pkill -f dunst &
pkill -f polybar &

bspc monitor -d tty code web social filemanager design 6

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 4
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true
bspc config single_monocle true

bspc rule -a URxvt desktop='^1' state=tiled follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a Google-chrome desktop='^3' state=tiled follow=on
bspc rule -a Ferdi desktop='^4' state=tiled follow=on
bspc rule -a Org.gnome.Nautilus desktop='^5' state=tiled follow=on
bspc rule -a zoom desktop='^5' state=tiled follow=on
bspc rule -a Gimp desktop='^6' state=tiled follow=on
bspc rule -a Loading.. desktop='^2' state=floating follow=on
bspc rule -a Peek state=floating follow=on
bspc rule -a Transmission-gtk desktop='^5' state=floating follow=on

sleep 1

feh --bg-scale ~/.dotfiles/background.jpg &

polybar main &

xset r rate 220 60 &

sxhkd &

dunst &

betterlockscreen -w &

mount | grep "$HOME/google-drive" >/dev/null || google-drive-ocamlfuse "$HOME/google-drive" -xdgbd &
